security:
    providers:
        usuarios:
            entity: {class: SgvsBundle\Entity\Usuario, property: nombreUsuario }

    encoders:
        SgvsBundle\Entity\Usuario: { algorithm: sha512, iterations: 10 }

    firewalls:
        sigeuats:
            pattern: ^/
            provider: usuarios
            anonymous: ~
            form_login:
                login_path: /login
                check_path: /login_check
                use_referer: true
                default_target_path: /
            remember_me:
                key: sigeuats
                lifetime: 3600
            logout:
                path: usuario_logout
                target: /login
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

    access_control:
        - { path: ^/install/*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/usuario/*, roles: ROLE_ADMIN }
        - { path: ^/, roles: ROLE_USUARIO }



    role_hierarchy:
        ROLE_ADMIN: [ROLE_USUARIO, ROLE_TECNICO, ROLE_CENTRO]
        ROLE_TECNICO: [ROLE_USUARIO]
        ROLE_CENTRO: [ROLE_USUARIO]
